### ISSUE TITLE
Support more/all options of :ssh_sftp.start_channel()

### ISSUE THREAD

**Issue by nmbrone** [i22-digitalagentur/sftp_client#19]
Hi there. 
Is there any way to pass an additional option to the underlying `:ssh_sftp.start_channel/3` call? I have to connect to a pretty outdated server and for that reason I need to modify configuration algorithms via the `modify_algorithms` option. It seems to be not possible right now since the option has to be listed in the Config struct.

**Comment by tlux** [comment]
Thanks for your feature request and sorry for the delay replying to this!

We should definitely support this as this becomes more relevant when using OTP 23. Maybe I would start implementing this on my own when I got more time, but pull requests are very welcome as well.
