### ISSUE TITLE
Upgrading to OTP 24 - returning "Key exchange failed" error on connecting. 

### ISSUE THREAD

**Issue by wkirschbaum** [i22-digitalagentur/sftp_client#26]
This is not a bug, but adding this for anyone experiencing the same issue in the future. 

OTP 24 disabled public key ssh-rsa  per default: https://github.com/erlang/otp/commit/59285df73841273adb111996cdb590ae1b86742b and it needs to be added manually if you are using it.

Is it worth it to add update the readme to add ssh-rsa to the config when upgrading to OTP 24?`
```
modify_algorithms: [
   append: [
      public_key: [:"ssh-rsa"]
    ]
]
```

**Comment by paulstatezny** [comment]
Thank you!!! It would be so wonderful if this were emphasized in the docs. Took me a while to arrive here. 😅

**Comment by iautom8things** [comment]
Thank you, this helped me!

**Comment by tlux** [comment]
Sorry for replying so late but I've been out of the Elixir game for a couple of months. I added a hint to the readme. Thanks everyone!

**Comment by paulstatezny** [comment]
Thank you @tlux !!!
