### ISSUE TITLE
How to make pub/priv key work with this client library

### ISSUE THREAD

**Issue by Dowwie** [i22-digitalagentur/sftp_client#29]
For the traveler who is struggling to get their private key to work:

1. you need to generate the key-pair in PEM format.  For instance, if you using ```ssh-keygen``` to create your keys:  ```ssh-keygen -t rsa -m PEM -f id_rsa -C"my@email.com"```

2. ed25519 does not seem to be compatible, at this time, with this client and/or the underlying ssh_sftp client.  rsa, however, works.

I found that when I specified a `user_dir` param with client config, ssh_file would generate a known_hosts file in the user_dir path with an algorithm I didn't even specify.  Not sure what's going on with that!  So, I am not using this parameter when connecting:

```elixir
{:ok, conn} =
      SFTPClient.connect(
      host: "localhost",
      port: 2022,
      user: "username",
      private_key_path: "absolute/path/to/private_key",
      sftp_vsn: 2
   )
```

Good luck.

**Comment by wkirschbaum** [comment]
If you don't want to use the filesystem you can also set the key_cb like below

```elixir
[
  key_cb: YourApp.SFTPKey,
]
```
```elixir
defmodule YourApp.SFTPKey do
  @behaviour :ssh_client_key_api
  ...
  ```
  
  If you want to read dynamically from env variable or db
