### ISSUE TITLE
add :sftp_client to "application" in the mix.exs file ?

### ISSUE THREAD

**Issue by jipen** [i22-digitalagentur/sftp_client#5]
For Elixir noobs (like me ;) ):

Mentionning to also add :

```
def application do
[ 
   applications: [:sftp_client, ...]
  ...
]
end 
```

in the readme.md ?

**Comment by tlux** [comment]
Were you having issues when not adding sftp_client to the applications option?

As SFTPClient officially runs only on Elixir > 1.8, specifying child applications should (generally) not be necessary.  Additionally, SFTPClient does not provide a supervision tree of its own. Thus, you can simply omit that option.

**Comment by jipen** [comment]
I just remember that I add some kind of errors and I just added that and then, no more error.
I don't remember what was the error but I'll give it a (re)try on thursday with my now working version , only removing :sftp_client from the application option to see if there's still an error when I launch my app.
BTW my Elixir version is 1.9.0.

**Comment by jipen** [comment]
My bad: I removed the :sftp_client from my application options and everything is OK.
The error surely came from one of my own bugs ! :)
Issue closed... Sorry !

**Comment by jipen** [comment]
Found it !
That happens when I make and run a release:
set MIX_ENV=prod mix release
then myprogram start
then when I try a command (myprogram rpc "mycommand(args)":
=> crash and
`** (UndefinedFunctionError) function SFTPClient.connect/1 is undefined (module SFTPClient is not available)`
When I had :sftp_client to applications or extra_applications options in mix.exs, everything is OK.
Did I forget something when I made the release ?
