### ISSUE TITLE
stream_file bangs on SFTPClient.OperationError

### ISSUE THREAD

**Issue by zoten** [i22-digitalagentur/sftp_client#8]
Hi! First of all, thanks for the great work!
I bumped into an exception in a non-bang function running a simple download pipeline, when using code like

```
case SftpClient.stream_file(conn, path) do
  {:ok, data} -> do_something_with(data)
  {:error, reason} -> {:error, reason}
end
```

```
** (SFTPClient.OperationError) Operation failed: permission_denied
    (sftp_client) lib/sftp_client/operation_util.ex:37: SFTPClient.OperationUtil.may_bang!/1
    (elixir) lib/stream.ex:1392: anonymous fn/5 in Stream.resource/3
    (elixir) lib/enum.ex:3023: Enum.reverse/1
    (elixir) lib/enum.ex:2668: Enum.to_list/1
    (myapp) lib/worker.ex:433: Worker.download/2
```

Can't access the sftp at the moment, but the error is pretty clear

I'm using 1.3.5 but didn't see any related diff in last commits
Didn't dig into the problem yet, pretty noob in elixir, but will try to take a look (and in the meanwhile add some defensive try rescue :P )

**Comment by tlux** [comment]
Thanks for your bug report. I'm going to take a look at it later or tomorrow.

**Comment by tlux** [comment]
I'm afraid that the exception is raised when evaluating the stream in your `do_something_with_data` function. 

To clear things up: `stream_file` just creates the stream but does not evaluate it until you call `Enum.to_list/1` or `Stream.run/1`. In fact, `stream_file` and its brother `stream_file!` will only return an error or raise when you are trying to stream a non-regular file, such as a directory or symbolic link.

The general behavior is consistent with how `File.stream!/1` handles streaming. I agree that it might be a bit misleading. We should probably think about deprecating the non-bang version in the long run.
